[[services]]
name = "frontend"
builder = "dockerfile"
dockerfilePath = "frontend/Dockerfile"
buildContext = "frontend"
startCommand = "node server.js"
port = 3000

[[services]]
name = "backend"
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"
buildContext = "backend"
startCommand = "node index.js"
port = 5001
envVars = [
  "NODE_ENV=production",
  "PORT=5001",
  "MYSQL_DATABASE=service_db",
  "MYSQL_TABLE=products"
]
